[package]
name = "rs-clone"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
rustyline = "16.0.0"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.8.23"
walkdir = "2.5.0"
